// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckInternet():Promise<boolean>;

export function CheckNetworkCompliance(arg1:string):Promise<main.ComplianceResult>;

export function ExecuteCommand(arg1:string):Promise<string>;

export function ExportLogs(arg1:string):Promise<void>;

export function GetAppVersion():Promise<string>;

export function SaveAuditResult(arg1:Record<string, any>):Promise<void>;

export function SyncAuditResults():Promise<void>;
