// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteCommand(arg1) {
  return window['go']['main']['App']['ExecuteCommand'](arg1);
}

export function ExportLogs(arg1) {
  return window['go']['main']['App']['ExportLogs'](arg1);
}
