// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckInternet() {
  return window['go']['main']['App']['CheckInternet']();
}

export function CheckNetworkCompliance(arg1) {
  return window['go']['main']['App']['CheckNetworkCompliance'](arg1);
}

export function ExecuteCommand(arg1) {
  return window['go']['main']['App']['ExecuteCommand'](arg1);
}

export function ExportLogs(arg1) {
  return window['go']['main']['App']['ExportLogs'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function SaveAuditResult(arg1) {
  return window['go']['main']['App']['SaveAuditResult'](arg1);
}

export function SyncAuditResults() {
  return window['go']['main']['App']['SyncAuditResults']();
}
